### ISSUE TITLE
New story not showing up on page

### ISSUE THREAD

**Issue by jrstorment** [finopsfoundation/fodo#24]
Trying to get this story to show up here but it's not coming across, what did I do wrong?

https://github.com/finopsfoundation/fodo/blob/master/_stories/story-5.md

https://framework.finops.org/framework/functions/commitment-discounts/

**Comment by andrewnhem** [comment]
I added a fix here: https://github.com/finopsfoundation/fodo/commit/7626fd6de8245c8c1363f941ce4b337c9eca3183

Should reflect live in a moment: https://framework.finops.org/framework/functions/commitment-discounts/

**Comment by andrewnhem** [comment]
Tested and it works @jrstorment @stevetrask
